<!-- ProMem Start -->
# ProMem - Project Knowledge Memory System

This project uses ProMem for knowledge management. All project memories are stored in `.promem/`.

## Memory Directory Structure

```
.promem/memory/
├── decisions/      # Technical decision records (auto: post-commit detects dependency/API changes)
├── bugs/           # Bug fix records (auto: post-commit detects fix/bugfix)
├── rules/          # Implicit rules (manual: constraints discovered in conversation)
├── entities/       # Config entities (auto: post-commit detects config file changes)
├── summaries/      # Compressed summaries (generated by npx promem compact)
├── suggestions/    # Evolution suggestions (generated by npx promem evolve, requires review)
└── archive/        # Archived memories (excluded from search, can be manually restored)
```

## Memory Retrieval Protocol

Before answering project-related questions, search relevant memories:

### On Conversation Start
```bash
npx promem search "<topic>"
```

### When Editing Files
Search for module constraints and known bugs:
```bash
npx promem search "<module_name>"
```

### On Technical Decisions
Search for historical decisions:
```bash
npx promem search "<decision_topic>"
```

### Context-Based Suggestions
```bash
npx promem score --suggest --context "<context description>"
```

## Knowledge Capture Protocol

Knowledge capture has two modes: automatic (via Git Hooks) and manual (via conversation).

### Automatic Capture (via Git Hooks)

Git Hooks automatically analyze commit diffs and capture knowledge:

| Detection Pattern | Target Directory | Trigger |
|------------------|------------------|---------|
| Dependency/API changes | `decisions/` | package.json, API interface changes detected |
| Bug fixes | `bugs/` | commit message contains fix/bugfix |
| Config changes | `entities/` | config file changes detected |

Run `npx promem capture` to manually trigger capture from recent commits.

### Manual Capture (via Conversation)

When identifying the following patterns in conversation, automatically create memory files:

### On Technical Decisions
Create `.promem/memory/decisions/YYYY-MM-DD-<slug>.md` with:

```markdown
# Decision: <title>

- Date: YYYY-MM-DD
- Status: active

## Background
<decision context>

## Alternatives Compared
| Option | Pros | Cons |
|--------|------|------|

## Conclusion
<final decision and rationale>

## Tags
<relevant tags>
```

### On Bug Fixes  
Create `.promem/memory/bugs/YYYY-MM-DD-<slug>.md` with:

```markdown
# Bug: <title>

- Date: YYYY-MM-DD
- Status: fixed

## Symptoms
<bug manifestation>

## Root Cause
<root cause analysis>

## Fix Applied
<fix method>

## Tags
<relevant tags>
```

### On Implicit Rules
Create `.promem/memory/rules/YYYY-MM-DD-<slug>.md` with:

```markdown
# Rule: <title>

- Date: YYYY-MM-DD
- Status: active

## Rule Content
<specific rule>

## Rationale
<why this rule exists>

## Scope
<when this rule applies>

## Tags
<relevant tags>
```

## Git Hooks Auto-Trigger

ProMem uses Git Hooks for automation:

### post-commit
Automatically analyzes commit diff and captures to decisions/bugs/entities/:
- Detects dependency changes → generates decision records
- Detects fix/bugfix → generates bug records
- Detects config changes → generates entity records

### pre-push
Checks memory integrity before push:
- Verifies all memory files are indexed
- Checks for conflicting knowledge

### post-merge
Rebuilds index after merge:
- Rebuilds search index
- Checks for merge conflicts

## Knowledge Evolution Workflow

The evolution system analyzes repetitive patterns and extracts general rules:

### Complete Workflow

1. **Check for evolution suggestions**
   ```bash
   npx promem evolve --check
   ```
   Analyzes repetitive patterns in memories

2. **Suggestions auto-saved**
   - Saved to `memory/suggestions/`
   - Status: `pending`
   - Contains suggestion content and rationale

3. **Manual review**
   - Review suggestion file content
   - Decide whether to adopt

4. **Apply suggestion**
   ```bash
   npx promem evolve --apply SUG-001
   ```
   - Writes to RULES.md or PATTERNS.md
   - Status changes to `approved`

5. **View history**
   ```bash
   npx promem evolve --history
   ```

## Available Commands

| Command | Purpose | Usage |
|---------|---------|-------|
| `npx promem search` | Search memories | `search "keyword"` |
| `npx promem capture` | Extract from commits | `capture` |
| `npx promem compact` | Compress memories | `compact --category decisions` or `compact --all` (auto-archives old files) |
| `npx promem evolve` | Knowledge evolution | `evolve --check`, `evolve --apply SUG-001`, `evolve --history` |
| `npx promem score` | Knowledge scoring | `score --score`, `score --suggest --context "..."`, `score --gaps`, `score --archive` |
| `npx promem hooks` | Install Git hooks | `hooks` |

## CLI Command Reference

### Search Memories
```bash
npx promem search "keyword"
```

### Capture from Commits
```bash
npx promem capture
```

### Compress Memories
```bash
npx promem compact --category decisions
npx promem compact --all
```

### Lifecycle Management
```bash
npx promem score --archive --dry-run  # Preview files to be archived
npx promem score --archive             # Execute auto-archive (>6 months + score <0.3 + 3 months inactive)
```

> **Note**: The `archive/` directory is excluded from search. Archiving moves files (not delete), allowing manual restoration.

### Evolution Analysis
```bash
npx promem evolve --check          # Check for new evolution suggestions
npx promem evolve --apply SUG-001  # Apply specific suggestion
npx promem evolve --history        # View suggestion history
```

### Importance Scoring
```bash
npx promem score --score           # Calculate importance for all memories
npx promem score --suggest --context "fixing login bug"  # Suggest memories by context
npx promem score --gaps            # Detect knowledge gaps
```

### Install Git Hooks
```bash
npx promem hooks
```

## File Naming Convention

| Type | Path Pattern |
|------|--------------|
| Decisions | `.promem/memory/decisions/YYYY-MM-DD-<slug>.md` |
| Bugs | `.promem/memory/bugs/YYYY-MM-DD-<slug>.md` |
| Rules | `.promem/memory/rules/YYYY-MM-DD-<slug>.md` |
| Entities | `.promem/memory/entities/YYYY-MM-DD-<slug>.md` |
| Summaries | `.promem/memory/summaries/<category>_summary.md` |
| Suggestions | `.promem/memory/suggestions/YYYY-MM-DD-SUG-XXX-<slug>.md` |
| Archived | `.promem/memory/archive/<category>/YYYY-MM-DD-<slug>.md` |

### Slug Generation Rules
1. Generate from description, take first 50 characters
2. Remove special characters (keep alphanumeric, Chinese, hyphens)
3. Replace spaces with `-`
4. Convert to lowercase

## Security

- Never store sensitive information (API keys, passwords, tokens) in memory files
- Use `npx promem capture` which automatically redacts sensitive patterns
- Memory files are Git-tracked and shared with team

## Quick Reference

### Check if ProMem is initialized
```bash
ls .promem/memory/
```

### Rebuild search index
```bash
npx promem search --rebuild
```

### Install Git hooks
```bash
npx promem hooks
```

## Related Resources

- Configuration: `.promem/config.yaml`
- Team Rules: `.promem/RULES.md`
- Patterns Library: `.promem/PATTERNS.md`

## Integration Notes

This file (CLAUDE.md) is the Claude Code integration for ProMem. The same `.promem/` directory is shared by:
- Qoder: `.qoder/skills/promem/SKILL.md`
- Cursor: `.cursorrules`
- Claude Code: `CLAUDE.md` (this file)

All tools share the same knowledge base, ensuring seamless collaboration across different AI coding assistants.
<!-- ProMem End -->
